# Generated by Django 4.1.3 on 2022-12-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tipo_documento',
            new_name='TipoDocumento',
        ),
    ]
