# Generated by Django 4.1.3 on 2022-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_tipo_documento_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
