# Generated by Django 4.1.3 on 2022-12-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_magnitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=5)),
                ('magnitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.magnitud')),
            ],
        ),
    ]
