# Generated by Django 4.1.3 on 2022-12-09 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_proveedor_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloVencimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=20)),
                ('fecha_factura', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('importe', models.FloatField()),
                ('estato', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.proveedor')),
            ],
        ),
    ]
