# Generated by Django 4.1.3 on 2022-12-10 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_modulovencimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
