# Generated by Django 4.1.3 on 2024-05-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_estadocorporalanimal_lactancia_razaanimal_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProductivoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
    ]
