name: CI-build and push image

on:
    push:
        branches:
            - main

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Docker Hub Login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }} 
                password: ${{ secrets.DOCKER_HUB_PASSWORD }} 
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: chrisarbe/devops_bootcamp_cf:latest